# -*- encoding: utf-8 -*-

import palette_a
import palette_b
import palette_c
import palette_d
import palette_e
import palette_f
import segment_01
import segment_02
import segment_03a
import segment_03b
import segment_04
import segment_05
import segment_06
import segment_07
import segment_08
import segment_09
import segment_10a
import segment_10b
import segment_10c
import segment_10d
import segment_11
import segment_12a
import segment_12b
import segment_13
import segment_14
import segment_15
import segment_16
import segment_17a
import segment_17b
